import { Check, Flame, Vote, X } from "lucide-react";
import { getPrismaClient } from "@habitat/db/client";
import { PollCloseField } from "@/components/poll-close-field";
import { requireRole } from "@/lib/authorization";
import { closeServerPoll, createServerPoll, resolveWakeRequest } from "./actions";

const db = getPrismaClient();

export default async function AdminCommunityPage() {
  await requireRole("ADMIN");
  const [requests, worlds, poll] = await Promise.all([
    db.wakeRequest.findMany({ where: { status: "PENDING" }, include: { server: { select: { displayName: true, worldName: true } }, requester: { select: { name: true, displayName: true } }, _count: { select: { votes: true } } }, orderBy: { requestedAt: "asc" } }),
    db.gameServer.findMany({ where: { enabled: true }, select: { id: true, displayName: true, worldName: true }, orderBy: { displayName: "asc" } }),
    db.serverPoll.findFirst({ where: { status: "ACTIVE" }, include: { options: { include: { server: { select: { displayName: true } }, _count: { select: { votes: true } } }, orderBy: { position: "asc" } } }, orderBy: { createdAt: "desc" } }),
  ]);
  return <section className="page-shell"><div className="page-intro"><p className="eyebrow">Habitat administration</p><h1>Community</h1><p>Review wake requests and open one game-night poll. Approval records community intent only; server control is not connected here.</p></div><div className="admin-community-grid"><section className="server-editor"><div className="server-editor-heading"><div><p className="eyebrow">Wake requests</p><h2>Light the Fire</h2></div><Flame aria-hidden="true" size={18} /></div>{requests.length === 0 ? <div className="chronicle-empty"><p>No pending requests.</p><span>Sleeping worlds can collect support here when members want them awake.</span></div> : <div className="wake-request-list">{requests.map((request) => <article key={request.id}><div><p className="eyebrow">{request._count.votes} supporters</p><h3>{request.server.displayName}</h3><p>{request.server.worldName} requested by {request.requester.displayName ?? request.requester.name ?? "Habitat member"}</p></div><div className="claim-decision"><form action={resolveWakeRequest}><input name="wakeRequestId" type="hidden" value={request.id} /><input name="status" type="hidden" value="APPROVED" /><button className="icon-action approve" title="Approve wake request" aria-label="Approve wake request"><Check aria-hidden="true" size={17} /></button></form><form action={resolveWakeRequest}><input name="wakeRequestId" type="hidden" value={request.id} /><input name="status" type="hidden" value="REJECTED" /><button className="icon-action reject" title="Reject wake request" aria-label="Reject wake request"><X aria-hidden="true" size={17} /></button></form></div></article>)}</div>}</section><section className="server-editor"><div className="server-editor-heading"><div><p className="eyebrow">Game night</p><h2>{poll ? "Active poll" : "Open a poll"}</h2></div><Vote aria-hidden="true" size={18} /></div>{poll ? <><p className="admin-poll-question">{poll.question}</p><div className="poll-result-list">{poll.options.map((option) => <p key={option.id}><span>{option.server.displayName}</span><strong>{option._count.votes}</strong></p>)}</div><form action={closeServerPoll}><input name="pollId" type="hidden" value={poll.id} /><button className="save-server" type="submit">Close poll</button></form></> : <form action={createServerPoll}><div className="server-editor-fields"><label className="field-wide">Question<input name="question" defaultValue="What are we playing tonight?" maxLength={100} required /></label><PollCloseField /></div><div className="world-choice-grid">{worlds.map((world) => <label key={world.id}><input name="serverIds" type="checkbox" value={world.id} /> <span>{world.displayName}</span><small>{world.worldName}</small></label>)}</div><button className="save-server" type="submit">Open poll</button></form>}</section></div></section>;
}
