ALTER TYPE "AchievementRuleType" ADD VALUE IF NOT EXISTS 'GAME_EVENT_COUNT';
ALTER TYPE "AchievementRewardKind" ADD VALUE IF NOT EXISTS 'MEDAL';
ALTER TYPE "AchievementRewardKind" ADD VALUE IF NOT EXISTS 'TROPHY';
