import { MessageCircle, Plus, Save, Send } from "lucide-react";
import { getPrismaClient } from "@habitat/db/client";
import { requireRole } from "@/lib/authorization";
import { saveDiscordConfiguration } from "./actions";

const db = getPrismaClient();

export default async function AdminDiscordPage() {
  await requireRole("ADMIN");
  const configurations = await db.discordGuildConfig.findMany({ include: { _count: { select: { notifications: true } } }, orderBy: { createdAt: "asc" } });
  return <section className="page-shell"><div className="page-intro"><p className="eyebrow">Habitat administration</p><h1>Discord</h1><p>Guild commands and major verified notices are configured here. Private bot credentials remain outside the portal.</p></div><div className="server-editor-list">{configurations.map((configuration) => <DiscordConfigurationForm configuration={configuration} key={configuration.id} />)}<DiscordConfigurationForm /></div></section>;
}

function DiscordConfigurationForm({ configuration }: { configuration?: { id: string; guildId: string; announcementChannelId: string | null; commandsEnabled: boolean; notificationsEnabled: boolean; notifyServerOnline: boolean; notifyServerSleeping: boolean; notifyServerOutage: boolean; notifyRecordBroken: boolean; notifyLegendaryAchievement: boolean; notifyWakeRequest: boolean; _count: { notifications: number } } }) {
  return <form action={saveDiscordConfiguration} className="server-editor"><input name="id" type="hidden" value={configuration?.id ?? ""} /><div className="server-editor-heading"><div><p className="eyebrow">{configuration ? `${configuration._count.notifications} queued or delivered notices` : "Guild binding"}</p><h2>{configuration ? "Discord server" : "Add Discord server"}</h2></div>{configuration ? <MessageCircle aria-hidden="true" size={18} /> : <Plus aria-hidden="true" size={18} />}</div><div className="server-editor-fields"><label className="field-wide">Discord server ID<input name="guildId" defaultValue={configuration?.guildId ?? ""} inputMode="numeric" maxLength={22} required /></label><label className="field-wide">Announcement channel ID<input name="announcementChannelId" defaultValue={configuration?.announcementChannelId ?? ""} inputMode="numeric" maxLength={22} /></label></div><div className="discord-toggle-grid"><label><input defaultChecked={configuration?.commandsEnabled ?? true} name="commandsEnabled" type="checkbox" /> Guild commands</label><label><input defaultChecked={configuration?.notificationsEnabled ?? true} name="notificationsEnabled" type="checkbox" /> Outbound notices</label><label><input defaultChecked={configuration?.notifyServerOnline ?? true} name="notifyServerOnline" type="checkbox" /> World online</label><label><input defaultChecked={configuration?.notifyServerSleeping ?? false} name="notifyServerSleeping" type="checkbox" /> Intentional rest</label><label><input defaultChecked={configuration?.notifyServerOutage ?? true} name="notifyServerOutage" type="checkbox" /> Unexpected outage</label><label><input defaultChecked={configuration?.notifyRecordBroken ?? true} name="notifyRecordBroken" type="checkbox" /> Record broken</label><label><input defaultChecked={configuration?.notifyLegendaryAchievement ?? true} name="notifyLegendaryAchievement" type="checkbox" /> Legendary achievement</label><label><input defaultChecked={configuration?.notifyWakeRequest ?? true} name="notifyWakeRequest" type="checkbox" /> Wake request</label></div><button className="save-server" type="submit">{configuration ? <Save aria-hidden="true" size={16} /> : <Send aria-hidden="true" size={16} />}{configuration ? "Save Discord server" : "Add Discord server"}</button></form>;
}
