import { bloomfallCreatureEnhancements } from "@/lib/bloomfall-creature-enhancements";

export const bloomfallAdaptiveP1P2Package = "bloomfall-adaptive-p1p2" as const;
export const bloomfallAdaptiveP1P2Version = "p1p2-owner-review-1" as const;

export const bloomfallAdaptiveP1P2Statuses = ["APPROVED_CANDIDATE", "REVISE", "REJECTED", "REUSED_V3", "REUSED_P0"] as const;
export type BloomfallAdaptiveP1P2Status = (typeof bloomfallAdaptiveP1P2Statuses)[number];

export type BloomfallAdaptiveP1P2Scores = {
  aaa: number; anatomy: number; materials: number; continuity: number;
  mutationLogic: number; artifact: number; canon: number; visualStorytelling: number;
};

export type BloomfallAdaptiveP1P2Asset = {
  id: string;
  entitySlug: "rootback-grazer" | "mirejaw" | "sump-eel" | "glasswing-kite" | "spore-lantern-colony" | "switchmother" | "old-drowner" | "maintenance-unit-m-17" | "the-bellwether";
  entity: string;
  state: string;
  purpose: "STATE_REFERENCE" | "HERO" | "CONTINUITY_REFERENCE" | "COMPARISON_REFERENCE" | "ENVIRONMENT_REFERENCE";
  filename: string;
  width: number;
  height: number;
  sha256: string;
  generationIteration: number | null;
  status: BloomfallAdaptiveP1P2Status;
  reusedAsset: "V3" | "P0" | null;
  codexDevelopmentBinding: string | null;
  physicalChanges: string;
  functionalChanges: string;
  continuityMarkers: readonly string[];
  matureTone: string;
  alt: string;
  scores: BloomfallAdaptiveP1P2Scores;
  reviewNote?: string;
};

const score = (aaa: number, anatomy: number, materials: number, continuity: number, mutationLogic: number, artifact: number, canon: number, visualStorytelling: number): BloomfallAdaptiveP1P2Scores =>
  ({ aaa, anatomy, materials, continuity, mutationLogic, artifact, canon, visualStorytelling });

/** Authoritative Prompt C2 manifest: the fourteen approved P1/P2 finals plus
 *  their locked V3 and P0 reuse. */
export const bloomfallAdaptiveP1P2Assets: readonly BloomfallAdaptiveP1P2Asset[] = [
  { id: "rootback-carried-mat", entitySlug: "rootback-grazer", entity: "Rootback Grazer", state: "Carried-Mat Grazer", purpose: "STATE_REFERENCE", filename: "rootback-grazer-carried-mat.png", width: 1122, height: 1402, sha256: "caff09e0e87a59be21ab7769f07925504b24581a25f8ed88a18a24bb2f419c38", generationIteration: 1, status: "APPROVED_CANDIDATE", reusedAsset: null, codexDevelopmentBinding: "rootback-grazer:known-states:0", physicalChanges: "Massive four-limbed grazer carrying an established living soil-and-root mat.", functionalChanges: "Moves seed, soil organisms, and modest filtration capacity through damaged ground.", continuityMarkers: ["broad herbivore skull", "left ear notch", "pale shoulder slash", "four load-bearing limbs", "continuous carried mat"], matureTone: "Rugged ecological unease, not predatory horror.", alt: "Carried-Mat Rootback Grazer crossing wet Mutation Belt ground.", scores: score(9.5, 9.7, 9.6, 9.7, 9.6, 9.7, 9.8, 9.5) },
  { id: "rootback-root-clamped", entitySlug: "rootback-grazer", entity: "Rootback Grazer", state: "Root-Clamped", purpose: "STATE_REFERENCE", filename: "rootback-grazer-root-clamped.png", width: 1122, height: 1402, sha256: "f53e55d332f2c19aeddfd2fc51773af3665d31d800cc5095ce9eba199fec21a3", generationIteration: 1, status: "APPROVED_CANDIDATE", reusedAsset: null, codexDevelopmentBinding: "rootback-grazer:known-states:1", physicalChanges: "The same root mat contracts around the flanks under a sealing resin film.", functionalChanges: "Lowers its center of mass and anchors contaminated surface flow.", continuityMarkers: ["same skull", "same ear notch", "same shoulder slash", "four limbs", "same mat footprint"], matureTone: "Functional tissue constriction without random gore.", alt: "Root-Clamped Rootback Grazer braced by contracted roots and resin.", scores: score(9.6, 9.7, 9.7, 9.8, 9.7, 9.7, 9.8, 9.6) },
  { id: "rootback-bastion-back", entitySlug: "rootback-grazer", entity: "Rootback Grazer", state: "Bastion-Back", purpose: "STATE_REFERENCE", filename: "rootback-grazer-bastion-back.png", width: 1122, height: 1402, sha256: "599cb95fcf56fe0c833e1d0e8682d6bc3bd3e19a5d43489d1177d8e4de85fb47", generationIteration: 1, status: "APPROVED_CANDIDATE", reusedAsset: null, codexDevelopmentBinding: "rootback-grazer:known-states:2", physicalChanges: "Barklike dermal lattice follows the load path beneath the mature carried ecology.", functionalChanges: "Spreads weight and holds failing terrain long enough for herd passage.", continuityMarkers: ["same skull", "same ear notch", "same shoulder slash", "four limbs", "same carried ecology"], matureTone: "Severe but protective symbiosis, never combat-monster spectacle.", alt: "Bastion-Back Rootback Grazer holding saturated terrain.", scores: score(9.6, 9.7, 9.8, 9.7, 9.8, 9.7, 9.8, 9.7) },

  { id: "mirejaw-flow-reader", entitySlug: "mirejaw", entity: "Mirejaw", state: "Flow-Reader", purpose: "STATE_REFERENCE", filename: "mirejaw-flow-reader.png", width: 1122, height: 1402, sha256: "12c29089b0074def89ffd780e807a7c6b41eba29b9ba09d256b2f1dedddb0286", generationIteration: 1, status: "APPROVED_CANDIDATE", reusedAsset: null, codexDevelopmentBinding: "mirejaw:known-states:0", physicalChanges: "Low amphibious body and flexible root-colored intake-fan jaw plates.", functionalChanges: "Reads flow, filters contaminated water, and pulls prey through a defended cut.", continuityMarkers: ["fixed jaw fan", "four amphibious limbs", "crescent shoulder mark", "two tail bands", "long tail"], matureTone: "Predatory feeding anatomy is graphic only where functional.", alt: "Flow-Reader Mirejaw opening its intake fan beneath the marsh waterline.", scores: score(9.6, 9.6, 9.7, 9.6, 9.8, 9.7, 9.8, 9.7) },
  { id: "mirejaw-silt-veiled", entitySlug: "mirejaw", entity: "Mirejaw", state: "Silt-Veiled", purpose: "STATE_REFERENCE", filename: "mirejaw-silt-veiled.png", width: 1122, height: 1402, sha256: "06cfa946c13bffb7f949ee385e5733440cf0177a51b08379262a4939f7894670", generationIteration: 1, status: "APPROVED_CANDIDATE", reusedAsset: null, codexDevelopmentBinding: "mirejaw:known-states:1", physicalChanges: "The same fan folds tight while silt film, chromatophores, and mucus seal vulnerable tissue.", functionalChanges: "Shelters through unstable chemistry at the cost of intake range.", continuityMarkers: ["same skull", "same four limbs", "same shoulder mark", "same tail bands", "closed original fan"], matureTone: "Claustrophobic marsh camouflage, restrained and plausible.", alt: "Silt-Veiled Mirejaw hiding low with its intake fan sealed.", scores: score(9.4, 9.5, 9.7, 9.7, 9.7, 9.7, 9.7, 9.5) },
  { id: "mirejaw-weir-plated", entitySlug: "mirejaw", entity: "Mirejaw", state: "Weir-Plated", purpose: "STATE_REFERENCE", filename: "mirejaw-weir-plated.png", width: 1122, height: 1402, sha256: "7b317465343e08071aed673fcee6506e7a485552c89e078539bd34423d924abc", generationIteration: 1, status: "APPROVED_CANDIDATE", reusedAsset: null, codexDevelopmentBinding: "mirejaw:known-states:2", physicalChanges: "Overlapping intake plates, broadened webbing, and limited load-point scutes reinforce the same body.", functionalChanges: "Anchors and filters in fast contaminated cuts while retaining flank counterplay.", continuityMarkers: ["same jaw fan", "same four limbs", "same shoulder mark", "same tail bands", "localized scutes"], matureTone: "Functional overadaptation produces the package's strongest animal horror.", alt: "Weir-Plated Mirejaw braced against a fast marsh channel.", scores: score(9.7, 9.7, 9.8, 9.8, 9.8, 9.7, 9.9, 9.8) },

  { id: "sump-eel-scavenger", entitySlug: "sump-eel", entity: "Sump Eel", state: "Sump Scavenger", purpose: "STATE_REFERENCE", filename: "sump-eel-sump-scavenger.png", width: 1122, height: 1402, sha256: "cdfac4ab247d51e4472d94655ebcb1d79dc6061eac83d23ce1408d84c78ddcac", generationIteration: 1, status: "APPROVED_CANDIDATE", reusedAsset: null, codexDevelopmentBinding: "sump-eel:known-states:0", physicalChanges: "Limbless eel with a fixed fin plan, lateral-line nodes, capacitor bands, and conductive mucus.", functionalChanges: "Scavenges industrial residue and carries brief charge through water networks.", continuityMarkers: ["same blunt head", "same fins", "same node row", "same band spacing", "same tail"], matureTone: "Dirty industrial naturalism rather than grotesque escalation.", alt: "Baseline Sump Eel beside a corroded drain intake.", scores: score(9.5, 9.8, 9.8, 9.8, 9.7, 9.8, 9.8, 9.6) },
  { id: "sump-eel-deep-charge", entitySlug: "sump-eel", entity: "Sump Eel", state: "Deep-Charge", purpose: "STATE_REFERENCE", filename: "sump-eel-deep-charge.png", width: 1122, height: 1402, sha256: "81ab749ef68142a9f1c0de5a40956d0acd5ca44b547fb7759397caa49c265b59", generationIteration: 1, status: "APPROVED_CANDIDATE", reusedAsset: null, codexDevelopmentBinding: "sump-eel:known-states:1", physicalChanges: "Only the existing bands, nodes, and insulating mucus thicken modestly.", functionalChanges: "Stores a larger internal charge without external lightning or a new body plan.", continuityMarkers: ["same blunt head", "same fins", "same node row", "same band spacing", "same silhouette"], matureTone: "Restrained conductive threat, never neon spectacle.", alt: "Deep-Charge Sump Eel with slightly thickened bands under dark mucus.", scores: score(9.6, 9.8, 9.8, 9.9, 9.8, 9.8, 9.9, 9.6) },

  { id: "glasswing-canonical", entitySlug: "glasswing-kite", entity: "Glasswing Kite", state: "Canonical Glasswing", purpose: "HERO", filename: "glasswing-kite-canonical-hero.png", width: 1672, height: 941, sha256: "7ac759e72c566358fe393ee6dc227c9711eeadf53c5796a56681d2845fc51c8c", generationIteration: 1, status: "APPROVED_CANDIDATE", reusedAsset: null, codexDevelopmentBinding: "glasswing-kite:canonical-form", physicalChanges: "One elegant fixed animal form with translucent mineralized wing struts.", functionalChanges: "Flock spacing, ringing struts, and flight posture warn of dangerous pressure.", continuityMarkers: ["two wings", "light aerodynamic body", "balanced tail", "fixed regional form"], matureTone: "Eerie beauty fits the species; grotesque anatomy would be off-canon.", alt: "Glasswing Kite flock banking beneath severe Crown Break pressure.", scores: score(9.7, 9.6, 9.8, 9.8, 9.8, 9.8, 9.9, 9.8) },
  { id: "lantern-canonical", entitySlug: "spore-lantern-colony", entity: "Spore Lantern Colony", state: "Canonical Lantern Colony", purpose: "HERO", filename: "spore-lantern-colony-canonical-hero.png", width: 1672, height: 941, sha256: "6cf88741f345480557207893ff9a4e5ad3deea14e0c22379d1e4ae2cdce1aac1", generationIteration: 1, status: "APPROVED_CANDIDATE", reusedAsset: null, codexDevelopmentBinding: "spore-lantern-colony:canonical-form", physicalChanges: "Porous mineral-organic shells hold animal, fungal, and algal tissue against wet roots.", functionalChanges: "A sessile symbiosis exchanges water and emits restrained ecological light.", continuityMarkers: ["substrate attachment", "animal pores", "mixed colony tissue", "fixed ecology"], matureTone: "Uncanny symbiosis, not a predatory or humanoid mushroom horror.", alt: "Warm Spore Lantern colonies anchored to dark Lantern Pool roots.", scores: score(9.7, 9.6, 9.9, 9.8, 9.9, 9.8, 9.9, 9.8) },
  { id: "switchmother-origin", entitySlug: "switchmother", entity: "Switchmother", state: "Engineered-Origin Structural Reference", purpose: "CONTINUITY_REFERENCE", filename: "switchmother-engineered-origin-reference.png", width: 1122, height: 1402, sha256: "50fbdffe13b467dc95793141cb8ef9a03f98dac7439ff03b7a962c4bb7f46ddd", generationIteration: 1, status: "APPROVED_CANDIDATE", reusedAsset: null, codexDevelopmentBinding: "switchmother:continuity:origin", physicalChanges: "An engineered biocapacitor test chassis shares plate, sac, anchor, and terminated-routing logic.", functionalChanges: "Establishes designed provenance without claiming an exact pre-Bloomfall individual.", continuityMarkers: ["three capacitor sacs", "insulating plates", "load anchors", "terminated cables", "engineered cradle"], matureTone: "Biological machinery is disturbing because its routing is understandable.", alt: "Engineered biocapacitor structure on a Southreach assembly cradle.", scores: score(9.6, 9.5, 9.8, 9.5, 9.8, 9.7, 9.8, 9.7) },
  { id: "old-drowner-lineage", entitySlug: "old-drowner", entity: "Old Drowner", state: "Probable-Lineage Reconstruction", purpose: "CONTINUITY_REFERENCE", filename: "old-drowner-probable-lineage-reconstruction.png", width: 1122, height: 1402, sha256: "f94d2f3c55c71ec5eecd4e88cded15ebaef3f3a33c9f113afb47efc3c733202e", generationIteration: 1, status: "APPROVED_CANDIDATE", reusedAsset: null, codexDevelopmentBinding: "old-drowner:continuity:probable-lineage", physicalChanges: "A plausible low amphibious Beasts-lineage frame with filter plates, four load limbs, and weighted tail.", functionalChanges: "Provides uncertain structural context, not an invented reusable species ladder.", continuityMarkers: ["broad filter skull", "four paddle limbs", "shoulder scar ring", "paired anchor ridges", "double tail band"], matureTone: "Somber field reconstruction; uncertainty is preserved.", alt: "Probable-lineage reconstruction for Old Drowner in shallow marsh water.", scores: score(9.4, 9.6, 9.7, 9.6, 9.7, 9.8, 9.8, 9.5) },
  { id: "old-drowner-hero", entitySlug: "old-drowner", entity: "Old Drowner", state: "Old Drowner at Drowned Intake", purpose: "HERO", filename: "old-drowner-drowned-intake-hero.png", width: 1672, height: 941, sha256: "34844185b2089e91132711daf20fe5edd129ec1aeb494cce75aaa25a8e117dae", generationIteration: 1, status: "APPROVED_CANDIDATE", reusedAsset: null, codexDevelopmentBinding: "old-drowner:continuity:current", physicalChanges: "The shared low frame is immense, scarred, mineralized, and root-weighted along real load paths.", functionalChanges: "Its body dams and redirects the Drowned Intake as a hydrological territory engineer.", continuityMarkers: ["same filter skull", "four paddle limbs", "same shoulder scar ring", "same tail bands", "long-term load growth"], matureTone: "Ancient bodily damage is severe but fully tied to hydrology.", alt: "Old Drowner redirecting floodwater through the ruined Drowned Intake.", scores: score(9.7, 9.6, 9.8, 9.7, 9.9, 9.8, 9.9, 9.9) },
  { id: "mender-integrated", entitySlug: "maintenance-unit-m-17", entity: "Maintenance Unit M-17 (Mender)", state: "Current Integrated Chassis", purpose: "HERO", filename: "mender-current-integrated-chassis-hero.png", width: 1672, height: 941, sha256: "57a02270eadf4b506e5c9f51f0040de7c40a35335d35519c58a803ce9f8b2de2", generationIteration: 2, status: "APPROVED_CANDIDATE", reusedAsset: null, codexDevelopmentBinding: "maintenance-unit-m-17:canonical-form", physicalChanges: "A low four-bogie crane chassis carries sorted tools, sensor fronds, cable roots, and tendon-repaired actuators.", functionalChanges: "Clamps and reseats a damaged pump coupling through a legible work sequence.", continuityMarkers: ["nonhumanoid load frame", "four bogies", "two unequal tools", "offset sensor mast", "purposeful organic repair"], matureTone: "Machine-organic horror comes from competent, ethically indifferent repair.", alt: "Mender's low integrated chassis repairing a damaged Southreach pump.", scores: score(9.8, 9.8, 9.9, 9.8, 9.9, 9.8, 9.9, 9.9) },

  { id: "reuse-switchmother-hero", entitySlug: "switchmother", entity: "Switchmother", state: "Current Exceptional Aberrant", purpose: "HERO", filename: "switchmother.png", width: 1672, height: 941, sha256: "53fc717810276550b2e43459134b7a104879ba019f85865357242bad22806ae1", generationIteration: null, status: "REUSED_V3", reusedAsset: "V3", codexDevelopmentBinding: "switchmother:continuity:current", physicalChanges: "Locked owner-approved engineered flesh, insulating plates, sacs, and switchgear integration.", functionalChanges: "Routes charge through a site-anchored biological-industrial network.", continuityMarkers: ["locked V3", "site anchored", "engineered lineage"], matureTone: "Owner-approved infrastructure horror.", alt: "Owner-approved Switchmother hero.", scores: score(9.6, 9.5, 9.7, 9.6, 9.9, 9.7, 10, 9.8) },
  { id: "reuse-bellwether-hero", entitySlug: "the-bellwether", entity: "The Bellwether", state: "Current Exceptional Aberrant", purpose: "HERO", filename: "the-bellwether.png", width: 1672, height: 941, sha256: "d68bc35a655fbcc2f9e66092b403710cf822838ee50e01b5c482ef70b6e11784", generationIteration: null, status: "REUSED_V3", reusedAsset: "V3", codexDevelopmentBinding: "the-bellwether:continuity:current", physicalChanges: "Locked owner-approved Hart-lineage exceptional anatomy.", functionalChanges: "Remains a singular ecological amplifier outside the ordinary Hart ladder.", continuityMarkers: ["locked V3", "Hart lineage", "exceptional break"], matureTone: "Rare ecological menace rather than generic mutation escalation.", alt: "Owner-approved Bellwether hero.", scores: score(9.5, 9.5, 9.5, 9.5, 9.7, 9.6, 10, 9.6) },
  { id: "reuse-hart-baseline", entitySlug: "the-bellwether", entity: "Blackbloom Hart", state: "Gradient-Sensing Hart", purpose: "COMPARISON_REFERENCE", filename: "blackbloom-hart-gradient-sensing.png", width: 1122, height: 1402, sha256: "d4c83effeef16abcda0971121db23fd784fcfbe7041e46c8aecd04b7fbf7c0d7", generationIteration: 1, status: "REUSED_P0", reusedAsset: "P0", codexDevelopmentBinding: "the-bellwether:continuity:hart-lineage", physicalChanges: "Locked P0 ordinary Hart baseline.", functionalChanges: "Makes the Bellwether's exceptional break legible without inventing intermediate forms.", continuityMarkers: ["locked P0", "ordinary Hart anatomy", "comparison only"], matureTone: "Neutral lineage evidence.", alt: "P0 Blackbloom Hart baseline used for Bellwether lineage comparison.", scores: score(9.4, 9.7, 9.3, 9.7, 9.7, 9.5, 9.7, 9.1) },
] as const;

export const bloomfallAdaptiveP1P2SelectedAssets = bloomfallAdaptiveP1P2Assets.filter((asset) => asset.status === "APPROVED_CANDIDATE");
export const bloomfallAdaptiveP1P2RejectedAssets = bloomfallAdaptiveP1P2Assets.filter((asset) => asset.status === "REJECTED");
export const bloomfallAdaptiveP1P2ReusedAssets = bloomfallAdaptiveP1P2Assets.filter((asset) => asset.status === "REUSED_V3" || asset.status === "REUSED_P0");
export const bloomfallAdaptiveP1P2GenerationSummary = { attempts: 15, revisedSubjects: 1, rejectedAttempts: 1 } as const;

const selectedByEntity = new Map<string, readonly BloomfallAdaptiveP1P2Asset[]>(
  [...new Set(bloomfallAdaptiveP1P2Assets.map((asset) => asset.entitySlug))].map((slug) => [slug, bloomfallAdaptiveP1P2Assets.filter((asset) => asset.entitySlug === slug && asset.status !== "REJECTED")]),
);

export function getBloomfallAdaptiveP1P2Presentation(entrySlug: string) {
  const enhancement = bloomfallCreatureEnhancements.find((entry) => entry.slug === entrySlug);
  if (!enhancement) return null;
  if (entrySlug === "bloommarked-remnant") return { kind: "NONE" as const, enhancement, assets: [] as readonly BloomfallAdaptiveP1P2Asset[] };
  const assets = selectedByEntity.get(entrySlug);
  if (!assets) return null;
  const orderedAssets = entrySlug === "the-bellwether" ? [...assets].sort((left, right) => Number(left.status !== "REUSED_P0") - Number(right.status !== "REUSED_P0")) : assets;
  const kind = enhancement.classification === "EXCEPTIONAL_ABERRANT" ? "EXCEPTIONAL" as const : enhancement.mutationEligibility === "NONE" ? "NONE" as const : "ADAPTIVE" as const;
  return { kind, enhancement, assets: orderedAssets };
}

export function bloomfallAdaptiveP1P2AssetUrl(asset: BloomfallAdaptiveP1P2Asset): string {
  const packageName = asset.reusedAsset === "V3" ? "bloomfall-v3" : asset.reusedAsset === "P0" ? "bloomfall-adaptive-p0" : asset.status === "REJECTED" ? "bloomfall-adaptive-p1p2-source" : bloomfallAdaptiveP1P2Package;
  return `/codex-art/${packageName}/${asset.filename}`;
}
