"use client";
/* eslint-disable no-empty -- malformed local JSON previews are ignored until the author fixes the draft */

import { useActionState, useMemo, useRef, useState } from "react";
import Link from "next/link";
import { AlertTriangle, BookOpen, CircleDot, GitBranch, MapPin, MousePointer2, Route, Save, Tags, Undo2, X } from "lucide-react";
import {
  type AtlasAuthorActionState,
  createAtlasConnection,
  createAtlasPointPlacement,
  deleteAtlasConnection,
  moveAtlasNode,
  removeAtlasConnectionPath,
  saveAtlasConnectionPath,
  splitAtlasBoundary,
  unplaceAtlasPoint,
  updateAtlasBoundary,
  updateAtlasConnection,
  updateAtlasPointPlacement,
} from "@/app/admin/story/atlas/actions";

const atlasAuthorInitialState: AtlasAuthorActionState = { status: "IDLE", message: "No unsaved server operation." };

type Point = readonly [number, number];
export type AtlasAuthoringData = {
  map: { id: string; slug: string; title: string; imageUrl: string; width: number; height: number };
  scenes: readonly { slug: string; title: string }[];
  nodes: readonly { id: string; x: number; y: number; version: number; boundaryIds: readonly string[] }[];
  boundaries: readonly { id: string; startNodeId: string; endNodeId: string; kind: "COAST" | "INTERNAL_BORDER" | "WATER_BOUNDARY" | "OPEN_BOUNDARY"; interiorVertices: readonly Point[]; version: number; regions: readonly string[] }[];
  placements: readonly { id: string; entryId: string; slug: string; title: string; x: number; y: number; labelX: number | null; labelY: number | null; minZoom: number; maxZoom: number | null; priority: number; version: number }[];
  unplaced: readonly { id: string; slug: string; title: string }[];
  entries: readonly { id: string; slug: string; title: string }[];
  connections: readonly { id: string; fromEntryId: string; fromTitle: string; toEntryId: string; toTitle: string; type: string; directionality: string; status: string; visibility: string; originalWording: string | null; editorialNotes: string | null; version: number; path: null | { id: string; geometry: { type: "LINESTRING"; coordinates: Point[] } | { type: "MULTILINESTRING"; coordinates: Point[][] }; minZoom: number; maxZoom: number | null; priority: number; version: number } }[];
  revisions: readonly { id: string; entityType: string; action: string; summary: string; actor: string; createdAt: string }[];
};

type Mode = "SELECT" | "REGIONS" | "POIS" | "LABELS" | "CONNECTIONS";
type Selection = { type: "NODE" | "BOUNDARY" | "POI" | "CONNECTION"; id: string } | null;

function linePoints(boundary: AtlasAuthoringData["boundaries"][number], nodes: Map<string, AtlasAuthoringData["nodes"][number]>) {
  const start = nodes.get(boundary.startNodeId); const end = nodes.get(boundary.endNodeId);
  return start && end ? [[start.x, start.y] as Point, ...boundary.interiorVertices, [end.x, end.y] as Point] : [];
}

function ActionStatus({ state }: { state: typeof atlasAuthorInitialState }) { return <p className={`atlas-author-status status-${state.status.toLowerCase()}`} aria-live="polite">{state.message}</p>; }

export function AtlasAuthoringWorkbench({ data }: { data: AtlasAuthoringData }) {
  const [authorMode, setAuthorMode] = useState(false); const [mode, setMode] = useState<Mode>("SELECT"); const [selection, setSelection] = useState<Selection>(null);
  const [draftNode, setDraftNode] = useState<{ id: string; x: number; y: number; originalX: number; originalY: number } | null>(null); const [dragging, setDragging] = useState(false);
  const [draftPoi, setDraftPoi] = useState<{ id: string; x: number; y: number; labelX: number | null; labelY: number | null } | null>(null);
  const [dragPoi, setDragPoi] = useState<"POSITION" | "LABEL" | null>(null);
  const [draftBoundary, setDraftBoundary] = useState<string>("[]"); const svgRef = useRef<SVGSVGElement>(null);
  const [dragBoundaryVertex, setDragBoundaryVertex] = useState<number | null>(null);
  const [selectedBoundaryVertex, setSelectedBoundaryVertex] = useState<number | null>(null);
  const [insertingBoundaryVertex, setInsertingBoundaryVertex] = useState(false);
  const [pathDraft, setPathDraft] = useState<Point[] | null>(null);
  const [dragPathVertex, setDragPathVertex] = useState<number | null>(null);
  const [connectionFilter, setConnectionFilter] = useState<"ALL" | "MISSING" | "AUTHORED">("ALL");
  const [nodeState, nodeAction, nodePending] = useActionState(moveAtlasNode, atlasAuthorInitialState);
  const [boundaryState, boundaryAction, boundaryPending] = useActionState(updateAtlasBoundary, atlasAuthorInitialState);
  const [splitState, splitAction, splitPending] = useActionState(splitAtlasBoundary, atlasAuthorInitialState);
  const [pointState, pointAction, pointPending] = useActionState(updateAtlasPointPlacement, atlasAuthorInitialState);
  const [placeState, placeAction, placePending] = useActionState(createAtlasPointPlacement, atlasAuthorInitialState);
  const [unplaceState, unplaceAction, unplacePending] = useActionState(unplaceAtlasPoint, atlasAuthorInitialState);
  const [connectionState, connectionAction, connectionPending] = useActionState(createAtlasConnection, atlasAuthorInitialState);
  const [updateConnectionState, updateConnectionAction, updateConnectionPending] = useActionState(updateAtlasConnection, atlasAuthorInitialState);
  const [deleteConnectionState, deleteConnectionAction, deleteConnectionPending] = useActionState(deleteAtlasConnection, atlasAuthorInitialState);
  const [pathState, pathAction, pathPending] = useActionState(saveAtlasConnectionPath, atlasAuthorInitialState);
  const [removePathState, removePathAction, removePathPending] = useActionState(removeAtlasConnectionPath, atlasAuthorInitialState);
  const nodes = useMemo(() => new Map(data.nodes.map((node) => [node.id, draftNode?.id === node.id ? { ...node, x: draftNode.x, y: draftNode.y } : node])), [data.nodes, draftNode]);
  const boundaryDraftVertices = useMemo(() => { try { const value = JSON.parse(draftBoundary) as unknown; return Array.isArray(value) && value.every((point) => Array.isArray(point) && point.length === 2 && point.every(Number.isSafeInteger)) ? value as Point[] : null; } catch { return null; } }, [draftBoundary]);
  const selectedNode = selection?.type === "NODE" ? data.nodes.find((item) => item.id === selection.id) : null;
  const selectedBoundary = selection?.type === "BOUNDARY" ? data.boundaries.find((item) => item.id === selection.id) : null;
  const selectedPoi = selection?.type === "POI" ? data.placements.find((item) => item.id === selection.id) : null;
  const selectedConnection = selection?.type === "CONNECTION" ? data.connections.find((item) => item.id === selection.id) : null;
  const dirty = Boolean(draftNode && selectedNode && (draftNode.x !== selectedNode.x || draftNode.y !== selectedNode.y)) || Boolean(draftPoi && selectedPoi && (draftPoi.x !== selectedPoi.x || draftPoi.y !== selectedPoi.y || draftPoi.labelX !== selectedPoi.labelX || draftPoi.labelY !== selectedPoi.labelY)) || Boolean(selectedBoundary && draftBoundary !== JSON.stringify(selectedBoundary.interiorVertices)) || pathDraft !== null;
  const pointerPoint = (event: React.MouseEvent<SVGSVGElement> | React.PointerEvent<SVGSVGElement>) => { const box = svgRef.current!.getBoundingClientRect(); return { x: Math.max(0, Math.min(data.map.width, Math.round((event.clientX - box.left) / box.width * data.map.width))), y: Math.max(0, Math.min(data.map.height, Math.round((event.clientY - box.top) / box.height * data.map.height))) }; };
  const chooseNode = (node: AtlasAuthoringData["nodes"][number]) => { setSelection({ type: "NODE", id: node.id }); setDraftNode({ id: node.id, x: node.x, y: node.y, originalX: node.x, originalY: node.y }); };
  const chooseBoundary = (boundary: AtlasAuthoringData["boundaries"][number]) => { setSelection({ type: "BOUNDARY", id: boundary.id }); setDraftBoundary(JSON.stringify(boundary.interiorVertices)); setSelectedBoundaryVertex(null); setInsertingBoundaryVertex(false); };
  const choosePoi = (point: AtlasAuthoringData["placements"][number]) => { setSelection({ type: "POI", id: point.id }); setDraftPoi({ id: point.id, x: point.x, y: point.y, labelX: point.labelX, labelY: point.labelY }); };
  const chooseConnection = (connection: AtlasAuthoringData["connections"][number]) => { setMode("CONNECTIONS"); setSelection({ type: "CONNECTION", id: connection.id }); setPathDraft(null); };
  const changeMode = (next: Mode) => { if (dirty && !window.confirm("Discard unsaved Atlas preview changes?")) return; setMode(next); setSelection(null); setDraftNode(null); setDraftPoi(null); setDraftBoundary("[]"); setPathDraft(null); setSelectedBoundaryVertex(null); setInsertingBoundaryVertex(false); };
  const visibleConnections = data.connections.filter((connection) => connectionFilter === "ALL" || (connectionFilter === "MISSING" ? !connection.path : Boolean(connection.path)));

  return <section className="atlas-author-workbench">
    <header className="atlas-author-header"><div><p className="eyebrow">Development-only · ADMIN · {data.map.slug}</p><h1>Atlas Authoring</h1><p>Canonical coordinates, shared topology, Codex placements, and scene-specific routes. Saves are explicit and revisioned.</p><nav className="atlas-author-scenes" aria-label="Atlas authoring scene">{data.scenes.map((scene) => <Link className={scene.slug === data.map.slug ? "active" : ""} key={scene.slug} href={scene.slug === "martino-world" ? "/admin/story/atlas" : `/admin/story/atlas?scene=${scene.slug}`}>{scene.title}</Link>)}</nav></div><div className="atlas-author-actions"><Link href={data.map.slug === "martino-world" ? "/codex/map?atlas=v2" : `/codex/map?atlas=v2&scene=${data.map.slug}`}>Preview Player View</Link><button onClick={() => { if (dirty && !window.confirm("Exit and discard unsaved preview changes?")) return; setAuthorMode((value) => !value); setMode("SELECT"); }}>{authorMode ? <><X size={15}/> Exit Author Mode</> : <><BookOpen size={15}/> Edit Atlas</>}</button></div></header>
    {!authorMode ? <div className="atlas-author-locked"><CircleDot size={24}/><div><h2>Player-safe preview</h2><p>Editor handles are hidden. Enter Author Mode to expose controlled tools.</p></div></div> : <>
      <nav className="atlas-mode-bar" aria-label="Atlas editor mode">{(["SELECT", "REGIONS", "POIS", "LABELS", "CONNECTIONS"] as Mode[]).map((item) => <button className={mode === item ? "active" : ""} key={item} onClick={() => changeMode(item)}>{item === "SELECT" ? <MousePointer2 size={14}/> : item === "REGIONS" ? <GitBranch size={14}/> : item === "POIS" ? <MapPin size={14}/> : item === "LABELS" ? <Tags size={14}/> : <Route size={14}/>} {item}</button>)}</nav>
      <div className="atlas-author-grid"><div className="atlas-author-map"><svg ref={svgRef} viewBox={`0 0 ${data.map.width} ${data.map.height}`} onClick={(event) => { const point = pointerPoint(event); if (mode === "REGIONS" && insertingBoundaryVertex && selectedBoundary && boundaryDraftVertices) { setDraftBoundary(JSON.stringify([...boundaryDraftVertices, [point.x, point.y]])); setSelectedBoundaryVertex(boundaryDraftVertices.length); setInsertingBoundaryVertex(false); return; } if (mode === "CONNECTIONS" && pathDraft !== null && dragPathVertex === null) setPathDraft([...pathDraft, [point.x, point.y]]); }} onPointerMove={(event) => { const point = pointerPoint(event); if (dragging && draftNode) setDraftNode({ ...draftNode, ...point }); if (dragBoundaryVertex !== null && boundaryDraftVertices) setDraftBoundary(JSON.stringify(boundaryDraftVertices.map((vertex, index) => index === dragBoundaryVertex ? [point.x, point.y] : vertex))); if (dragPoi && draftPoi) setDraftPoi(dragPoi === "POSITION" ? { ...draftPoi, x: point.x, y: point.y } : { ...draftPoi, labelX: point.x, labelY: point.y }); if (dragPathVertex !== null && pathDraft) setPathDraft(pathDraft.map((vertex, index) => index === dragPathVertex ? [point.x, point.y] : vertex)); }} onPointerUp={() => { setDragging(false); setDragBoundaryVertex(null); setDragPoi(null); setDragPathVertex(null); }} onPointerLeave={() => { setDragging(false); setDragBoundaryVertex(null); setDragPoi(null); setDragPathVertex(null); }}>
        <image href={data.map.imageUrl} width={data.map.width} height={data.map.height}/>
        {(mode === "REGIONS" || mode === "SELECT") && data.boundaries.map((boundary) => { const preview = selection?.type === "BOUNDARY" && selection.id === boundary.id && boundaryDraftVertices ? { ...boundary, interiorVertices: boundaryDraftVertices } : boundary; return <polyline className={selection?.type === "BOUNDARY" && selection.id === boundary.id ? "selected" : ""} key={boundary.id} points={linePoints(preview, nodes).map((point) => point.join(",")).join(" ")} onClick={(event) => { event.stopPropagation(); chooseBoundary(boundary); }}/>; }) }
        {(mode === "REGIONS" || mode === "SELECT") && [...nodes.values()].map((node) => <circle className={selection?.type === "NODE" && selection.id === node.id ? "selected" : ""} key={node.id} cx={node.x} cy={node.y} r={selection?.type === "NODE" && selection.id === node.id ? 480 : 300} onPointerDown={(event) => { event.preventDefault(); chooseNode(node); if (mode === "REGIONS") { setDragging(true); event.currentTarget.setPointerCapture(event.pointerId); } }}/>) }
        {mode === "REGIONS" && selectedBoundary && boundaryDraftVertices ? boundaryDraftVertices.map((point, index) => <circle className={`boundary-vertex ${selectedBoundaryVertex === index ? "selected" : ""}`} key={`${selectedBoundary.id}-${index}`} cx={point[0]} cy={point[1]} r={320} onPointerDown={(event) => { event.preventDefault(); event.stopPropagation(); setSelectedBoundaryVertex(index); setDragBoundaryVertex(index); event.currentTarget.setPointerCapture(event.pointerId); }}/>) : null}
        {(mode === "POIS" || mode === "LABELS" || mode === "SELECT") && data.placements.map((point) => { const draft = draftPoi?.id === point.id ? draftPoi : point; const labelX = draft.labelX ?? draft.x + 600; const labelY = draft.labelY ?? draft.y - 500; return <g key={point.id} onClick={(event) => { event.stopPropagation(); choosePoi(point); }}><circle className={`poi ${selection?.type === "POI" && selection.id === point.id ? "selected" : ""}`} cx={draft.x} cy={draft.y} r={420} onPointerDown={(event) => { event.preventDefault(); event.stopPropagation(); choosePoi(point); if (mode === "POIS") { setDragPoi("POSITION"); event.currentTarget.setPointerCapture(event.pointerId); } }}/><text x={labelX} y={labelY}>{point.title}</text>{mode === "LABELS" ? <circle className="label-anchor" cx={labelX} cy={labelY} r={240} onPointerDown={(event) => { event.preventDefault(); event.stopPropagation(); choosePoi(point); setDraftPoi({ id: point.id, x: point.x, y: point.y, labelX, labelY }); setDragPoi("LABEL"); event.currentTarget.setPointerCapture(event.pointerId); }}/> : null}</g>; })}
        {mode === "CONNECTIONS" && data.connections.flatMap((connection) => connection.path ? (connection.path.geometry.type === "LINESTRING" ? [connection.path.geometry.coordinates] : connection.path.geometry.coordinates).map((line, index) => <polyline className={`route route-${connection.type.toLowerCase()} ${selection?.type === "CONNECTION" && selection.id === connection.id ? "selected" : ""}`} key={`${connection.id}-${index}`} points={line.map((point) => point.join(",")).join(" ")} onClick={(event) => { event.stopPropagation(); chooseConnection(connection); }}/>) : [])}
        {mode === "CONNECTIONS" && pathDraft !== null ? <><polyline className="route selected route-draft" points={pathDraft.map((point) => point.join(",")).join(" ")}/>{pathDraft.map((point, index) => <circle className="route-vertex" key={`${point.join("-")}-${index}`} cx={point[0]} cy={point[1]} r={360} onPointerDown={(event) => { event.preventDefault(); event.stopPropagation(); setDragPathVertex(index); event.currentTarget.setPointerCapture(event.pointerId); }}/>)}</> : null}
      </svg><p className="atlas-raster-note">Current raster evidence: 1536×1024. Editor coordinates remain fixed-point {data.map.width}×{data.map.height}.</p></div>
      <aside className="atlas-author-inspector">
        <div className="atlas-save-state"><strong>{dirty ? "Unsaved changes" : "Saved state"}</strong>{dirty ? <button onClick={() => { if (selectedNode) setDraftNode({ id: selectedNode.id, x: selectedNode.x, y: selectedNode.y, originalX: selectedNode.x, originalY: selectedNode.y }); if (selectedPoi) setDraftPoi({ id: selectedPoi.id, x: selectedPoi.x, y: selectedPoi.y, labelX: selectedPoi.labelX, labelY: selectedPoi.labelY }); if (selectedBoundary) setDraftBoundary(JSON.stringify(selectedBoundary.interiorVertices)); setPathDraft(null); }}><Undo2 size={13}/> Discard</button> : null}</div>
        {selectedNode && draftNode ? <form action={nodeAction}><h2>Topology node</h2><p>{selectedNode.boundaryIds.length} connected boundaries. Moving this shared junction changes every consuming region.</p><input type="hidden" name="id" value={selectedNode.id}/><input type="hidden" name="mapId" value={data.map.id}/><input type="hidden" name="expectedVersion" value={selectedNode.version}/><label>Atlas X<input name="x" type="number" value={draftNode.x} onChange={(event) => setDraftNode({ ...draftNode, x: Number(event.target.value) })}/></label><label>Atlas Y<input name="y" type="number" value={draftNode.y} onChange={(event) => setDraftNode({ ...draftNode, y: Number(event.target.value) })}/></label><button disabled={nodePending} type="submit"><Save size={14}/> Save shared node</button><ActionStatus state={nodeState}/></form> : null}
        {selectedBoundary ? <form action={boundaryAction}><h2>Shared boundary</h2><p>Shared by: {selectedBoundary.regions.join(", ") || "no area ring"}. Saving validates the complete affected topology.</p>{selectedBoundary.regions.length > 1 ? <p className="atlas-author-warning"><AlertTriangle size={13}/> This edit changes multiple regions.</p> : null}<input type="hidden" name="id" value={selectedBoundary.id}/><input type="hidden" name="mapId" value={data.map.id}/><input type="hidden" name="startNodeId" value={selectedBoundary.startNodeId}/><input type="hidden" name="endNodeId" value={selectedBoundary.endNodeId}/><input type="hidden" name="expectedVersion" value={selectedBoundary.version}/><label>Kind<select name="kind" defaultValue={selectedBoundary.kind}>{["COAST", "INTERNAL_BORDER", "WATER_BOUNDARY", "OPEN_BOUNDARY"].map((kind) => <option key={kind}>{kind}</option>)}</select></label><label>Interior vertices<textarea name="interiorVertices" rows={8} value={draftBoundary} onChange={(event) => setDraftBoundary(event.target.value)}/></label><div className="atlas-inline-actions"><button type="button" onClick={() => { try { const rows = JSON.parse(draftBoundary) as Point[]; setDraftBoundary(JSON.stringify([...rows, rows.at(-1) ?? [data.map.width / 2, data.map.height / 2]])); } catch {} }}>Insert vertex</button><button type="button" onClick={() => { try { const rows = JSON.parse(draftBoundary) as Point[]; setDraftBoundary(JSON.stringify(rows.slice(0, -1))); } catch {} }}>Delete last vertex</button></div><button disabled={boundaryPending} type="submit"><Save size={14}/> Save boundary</button><ActionStatus state={boundaryState}/></form> : null}
        {selectedPoi && draftPoi ? <><form action={pointAction}><h2>{mode === "LABELS" ? "Label anchor" : "POI placement"}</h2><strong>{selectedPoi.title}</strong><p>{mode === "POIS" ? "Drag the marker to preview its canonical position." : mode === "LABELS" ? "Drag the label anchor without moving the POI." : "Select an editing mode to drag."}</p><input type="hidden" name="id" value={selectedPoi.id}/><input type="hidden" name="mapId" value={data.map.id}/><input type="hidden" name="entryId" value={selectedPoi.entryId}/><input type="hidden" name="expectedVersion" value={selectedPoi.version}/><label>Position X<input name="x" type="number" value={draftPoi.x} onChange={(event) => setDraftPoi({ ...draftPoi, x: Number(event.target.value) })}/></label><label>Position Y<input name="y" type="number" value={draftPoi.y} onChange={(event) => setDraftPoi({ ...draftPoi, y: Number(event.target.value) })}/></label><label>Label X<input name="labelX" type="number" value={draftPoi.labelX ?? ""} onChange={(event) => setDraftPoi({ ...draftPoi, labelX: event.target.value === "" ? null : Number(event.target.value) })}/></label><label>Label Y<input name="labelY" type="number" value={draftPoi.labelY ?? ""} onChange={(event) => setDraftPoi({ ...draftPoi, labelY: event.target.value === "" ? null : Number(event.target.value) })}/></label><label>Minimum zoom<input name="minZoom" type="number" step="0.1" defaultValue={selectedPoi.minZoom}/></label><label>Maximum zoom<input name="maxZoom" type="number" step="0.1" defaultValue={selectedPoi.maxZoom ?? ""}/></label><label>Priority<input name="priority" type="number" defaultValue={selectedPoi.priority}/></label><button disabled={pointPending} type="submit"><Save size={14}/> Save placement</button><ActionStatus state={pointState}/></form><form action={unplaceAction}><input type="hidden" name="id" value={selectedPoi.id}/><input type="hidden" name="expectedVersion" value={selectedPoi.version}/><button className="danger" disabled={unplacePending} type="submit">Remove placement only</button><ActionStatus state={unplaceState}/></form></> : null}
        {selectedConnection ? <><h2>Connection</h2><strong>{selectedConnection.fromTitle} → {selectedConnection.toTitle}</strong><p>{selectedConnection.type} · {selectedConnection.directionality} · {selectedConnection.status}</p><div className="atlas-inline-actions"><button type="button" onClick={() => setPathDraft(selectedConnection.path?.geometry.type === "LINESTRING" ? [...selectedConnection.path.geometry.coordinates] : [])}>{selectedConnection.path ? "Edit vertices" : "Draw Path"}</button>{pathDraft !== null ? <><button type="button" disabled={pathDraft.length === 0} onClick={() => setPathDraft(pathDraft.slice(0, -1))}>Remove last vertex</button><button type="button" onClick={() => setPathDraft(null)}>Cancel drawing</button></> : null}</div><p>{pathDraft === null ? "Select Draw Path to edit a LineString on the map." : `${pathDraft.length} vertices · click the map to add · drag handles to move`}</p><form action={pathAction}><input type="hidden" name="id" value={selectedConnection.path?.id ?? ""}/><input type="hidden" name="expectedVersion" value={selectedConnection.path?.version ?? 1}/><input type="hidden" name="connectionId" value={selectedConnection.id}/><input type="hidden" name="mapId" value={data.map.id}/><label>Path geometry<textarea name="geometry" rows={8} value={JSON.stringify(pathDraft === null ? selectedConnection.path?.geometry ?? { type: "LINESTRING", coordinates: [] } : { type: "LINESTRING", coordinates: pathDraft }, null, 2)} onChange={(event) => { try { const value = JSON.parse(event.target.value) as { type: string; coordinates: Point[] }; if (value.type === "LINESTRING" && Array.isArray(value.coordinates)) setPathDraft(value.coordinates); } catch {} }}/></label><label>Minimum zoom<input name="minZoom" type="number" step="0.1" defaultValue={selectedConnection.path?.minZoom ?? 0}/></label><label>Maximum zoom<input name="maxZoom" type="number" step="0.1" defaultValue={selectedConnection.path?.maxZoom ?? ""}/></label><label>Priority<input name="priority" type="number" defaultValue={selectedConnection.path?.priority ?? 0}/></label><button disabled={pathPending || (pathDraft !== null && pathDraft.length < 2)} type="submit"><Save size={14}/> {selectedConnection.path ? "Update path" : "Create path"}</button><ActionStatus state={pathState}/></form>{selectedConnection.path ? <form action={removePathAction}><input type="hidden" name="id" value={selectedConnection.path.id}/><input type="hidden" name="expectedVersion" value={selectedConnection.path.version}/><button className="danger" disabled={removePathPending}>Remove path from this map</button><ActionStatus state={removePathState}/></form> : null}</> : null}
        {!selection ? <div className="atlas-author-empty"><MousePointer2 size={22}/><h2>Select map data</h2><p>SELECT is safe inspection. Choose a deliberate editing mode before changing coordinates.</p></div> : null}
        {selectedConnection ? <details className="atlas-connection-semantics"><summary>Edit semantic connection</summary><form action={updateConnectionAction}><input type="hidden" name="id" value={selectedConnection.id}/><input type="hidden" name="expectedVersion" value={selectedConnection.version}/><label>From<select name="fromEntryId" defaultValue={selectedConnection.fromEntryId}>{data.entries.map((entry) => <option value={entry.id} key={entry.id}>{entry.title}</option>)}</select></label><label>To<select name="toEntryId" defaultValue={selectedConnection.toEntryId}>{data.entries.map((entry) => <option value={entry.id} key={entry.id}>{entry.title}</option>)}</select></label><label>Type<select name="type" defaultValue={selectedConnection.type}>{["ROAD", "TRAIL", "RIVER_TRAVEL", "SEA_ROUTE", "AIR_ROUTE", "OTHER", "UNKNOWN"].map((value) => <option key={value}>{value}</option>)}</select></label><label>Direction<select name="directionality" defaultValue={selectedConnection.directionality}>{["UNSPECIFIED", "FROM_TO", "TO_FROM", "BIDIRECTIONAL"].map((value) => <option key={value}>{value}</option>)}</select></label><label>Status<select name="status" defaultValue={selectedConnection.status}>{["UNSPECIFIED", "OPEN", "CLOSED", "DESTROYED"].map((value) => <option key={value}>{value}</option>)}</select></label><label>Visibility<select name="visibility" defaultValue={selectedConnection.visibility}>{["DEFAULT", "HIDDEN"].map((value) => <option key={value}>{value}</option>)}</select></label><label>Authored wording<input name="originalWording" maxLength={2000} defaultValue={selectedConnection.originalWording ?? ""}/></label><label>Editorial notes<textarea name="editorialNotes" maxLength={2000} defaultValue={selectedConnection.editorialNotes ?? ""}/></label><button disabled={updateConnectionPending}><Save size={14}/> Update connection</button><ActionStatus state={updateConnectionState}/></form>{!selectedConnection.path ? <form action={deleteConnectionAction}><input type="hidden" name="id" value={selectedConnection.id}/><input type="hidden" name="expectedVersion" value={selectedConnection.version}/><label>Strong deletion confirmation<input name="confirmation" placeholder="DELETE WORLD CONNECTION"/></label><button className="danger" disabled={deleteConnectionPending}>Delete world connection</button><ActionStatus state={deleteConnectionState}/></form> : <p>Remove every scene path before semantic deletion is permitted.</p>}</details> : null}
        {selectedBoundary ? <details><summary>Split at existing interior vertex</summary><p>This atomic operation creates one shared node, replaces the edge with two edges, rewrites every consuming ring, and validates the complete map. Merge remains intentionally deferred.</p><form action={splitAction}><input type="hidden" name="id" value={selectedBoundary.id}/><input type="hidden" name="expectedVersion" value={selectedBoundary.version}/><label>Interior vertex index<input name="interiorVertexIndex" type="number" min="0" max={Math.max(0, selectedBoundary.interiorVertices.length - 1)} defaultValue="0"/></label><button disabled={splitPending || selectedBoundary.interiorVertices.length === 0}>Split boundary transactionally</button><ActionStatus state={splitState}/></form></details> : null}
        {selectedBoundary ? <div className="atlas-boundary-tools"><h3>Map vertex tools</h3><p>{boundaryDraftVertices?.length ?? 0} interior vertices. Drag a gold handle to move it. Endpoints remain shared topology nodes.</p><div className="atlas-inline-actions"><button type="button" className={insertingBoundaryVertex ? "active" : ""} onClick={() => setInsertingBoundaryVertex((value) => !value)}>{insertingBoundaryVertex ? "Click map to insert" : "Insert on map"}</button><button type="button" disabled={selectedBoundaryVertex === null || !boundaryDraftVertices} onClick={() => { if (selectedBoundaryVertex === null || !boundaryDraftVertices) return; setDraftBoundary(JSON.stringify(boundaryDraftVertices.filter((_point, index) => index !== selectedBoundaryVertex))); setSelectedBoundaryVertex(null); }}>Delete selected vertex</button></div></div> : null}
      </aside></div>
      <div className="atlas-author-lower"><section><h2>Unplaced Locations <span>{data.unplaced.length}</span></h2><form action={placeAction}><label>Canonical Codex entity<select name="entryId">{data.unplaced.map((entry) => <option key={entry.id} value={entry.id}>{entry.title}</option>)}</select></label><input type="hidden" name="mapId" value={data.map.id}/><label>X<input name="x" type="number" defaultValue={50000}/></label><label>Y<input name="y" type="number" defaultValue={Math.round(data.map.height / 2)}/></label><input type="hidden" name="labelX" value=""/><input type="hidden" name="labelY" value=""/><input type="hidden" name="minZoom" value="1.5"/><input type="hidden" name="maxZoom" value=""/><input type="hidden" name="priority" value="0"/><button disabled={placePending}>Preview position, then place</button><ActionStatus state={placeState}/></form></section>
      <section><h2>Connections <span>{data.connections.length}</span></h2><p>{data.connections.filter((item) => item.path).length} paths authored · {data.connections.filter((item) => !item.path).length} missing</p><div className="atlas-inline-actions" aria-label="Connection path filter">{(["ALL", "MISSING", "AUTHORED"] as const).map((filter) => <button type="button" className={connectionFilter === filter ? "active" : ""} key={filter} onClick={() => setConnectionFilter(filter)}>{filter}</button>)}</div><div className="atlas-connection-list">{visibleConnections.map((connection) => <button key={connection.id} onClick={() => chooseConnection(connection)}><span>{connection.fromTitle} → {connection.toTitle}</span><small>{connection.type} · {connection.path ? "has path" : "Connection exists · Path not authored"}</small></button>)}</div><details><summary>Add semantic connection</summary><form action={connectionAction}><label>From<select name="fromEntryId">{data.entries.map((entry) => <option value={entry.id} key={entry.id}>{entry.title}</option>)}</select></label><label>To<select name="toEntryId">{data.entries.map((entry) => <option value={entry.id} key={entry.id}>{entry.title}</option>)}</select></label><label>Type<select name="type">{["ROAD", "TRAIL", "RIVER_TRAVEL", "SEA_ROUTE", "AIR_ROUTE", "OTHER", "UNKNOWN"].map((value) => <option key={value}>{value}</option>)}</select></label><label>Direction<select name="directionality">{["UNSPECIFIED", "FROM_TO", "TO_FROM", "BIDIRECTIONAL"].map((value) => <option key={value}>{value}</option>)}</select></label><label>Status<select name="status">{["UNSPECIFIED", "OPEN", "CLOSED", "DESTROYED"].map((value) => <option key={value}>{value}</option>)}</select></label><label>Visibility<select name="visibility">{["DEFAULT", "HIDDEN"].map((value) => <option key={value}>{value}</option>)}</select></label><label>Authored wording<input name="originalWording" maxLength={2000}/></label><label>Editorial notes<textarea name="editorialNotes" maxLength={2000}/></label><button disabled={connectionPending}>Create connection</button><ActionStatus state={connectionState}/></form></details></section>
      <section><h2>Revision history</h2><ol className="atlas-revision-list">{data.revisions.map((revision) => <li key={revision.id}><strong>{revision.summary}</strong><span>{revision.action} · {revision.actor} · {new Date(revision.createdAt).toLocaleString()}</span></li>)}</ol></section></div>
    </>}
  </section>;
}
